import type { ConversionVocabulary } from "../labels";
import type { DailyPoint, MetricSnapshot } from "../metrics";
import type { CreativeType, CurrencyCode, EntityStatus, IsoDate } from "../types";

/**
 * The deterministic insight model. A finding is a computed statement about
 * one entity, with the evidence that proves it. Nothing here renders UI and
 * nothing here is generated by a language model.
 */

export type InsightPriority = "high" | "opportunity" | "watch";

export const PRIORITY_ORDER: readonly InsightPriority[] = ["high", "opportunity", "watch"];

export const PRIORITY_LABELS: Record<InsightPriority, string> = {
  high: "High impact",
  opportunity: "Opportunity",
  watch: "Watch",
};

export type DetectorId =
  | "zero_conversion_spend"
  | "campaign_deterioration"
  | "cpa_spike"
  | "roas_decline"
  | "ctr_deterioration"
  | "creative_fatigue"
  | "spend_concentration"
  | "underfunded_winner"
  | "campaign_improvement"
  | "scaling_winner";

export const DETECTOR_LABELS: Record<DetectorId, string> = {
  zero_conversion_spend: "Zero-conversion spend",
  campaign_deterioration: "Campaign deterioration",
  cpa_spike: "CPA spike",
  roas_decline: "ROAS decline",
  ctr_deterioration: "CTR deterioration",
  creative_fatigue: "Creative fatigue proxy",
  spend_concentration: "Spend concentration",
  underfunded_winner: "Underfunded winner",
  campaign_improvement: "Campaign improvement",
  scaling_winner: "Scaling winner",
};

export type InsightEntityType = "account" | "campaign" | "ad_set" | "ad" | "creative";

export const ENTITY_TYPE_LABELS: Record<InsightEntityType, string> = {
  account: "Account",
  campaign: "Campaign",
  ad_set: "Ad set",
  ad: "Ad",
  creative: "Creative",
};

export interface InsightEntity {
  type: InsightEntityType;
  id: string;
  name: string;
  /** Where the entity sits, e.g. the campaign an ad belongs to. */
  context: string | null;
}

/**
 * How a value is written: `money` whole currency, `cost` currency to two
 * decimals, `percent` a rate such as CTR, `share` a whole percentage of a
 * total, `multiple` ROAS, `count` an integer, `change` a signed relative change.
 */
export type ValueFormat =
  "money" | "cost" | "count" | "percent" | "share" | "multiple" | "change";

export interface EvidenceItem {
  label: string;
  value: number | null;
  format: ValueFormat;
  /** Relative change against the comparison period, when it proves the finding. */
  change?: number | null;
  higherIsBetter?: boolean | null;
  /** A short factual qualifier, e.g. "from £59.72" or "£110.83 over target". */
  note?: string;
  noteTone?: "positive" | "negative" | "muted";
}

/** One now / before / change row. */
export interface ComparisonRow {
  label: string;
  format: ValueFormat;
  current: number | null;
  previous: number | null;
  change: number | null;
  higherIsBetter: boolean | null;
}

export interface TargetRelation {
  metric: "cpa" | "roas";
  target: number;
  actual: number;
  /** Absolute distance from the target in the metric's unit. */
  difference: number;
  relation: "over" | "under" | "on";
  /** Whether the relation is good for the client (under a cost target, over a ROAS target). */
  favourable: boolean;
}

export interface SeriesPoint {
  date: IsoDate;
  value: number | null;
}

export interface InsightChart {
  title: string;
  format: ValueFormat;
  current: SeriesPoint[];
  /** Previous period aligned by day index. */
  previous: SeriesPoint[];
  /** Text equivalent of what the chart shows. */
  summary: string;
}

/** A small table that proves a relative claim (ads in a campaign, campaign shares). */
export interface InsightBreakdown {
  title: string;
  columns: Array<{ label: string; format: ValueFormat }>;
  rows: Array<{ id: string; label: string; highlight: boolean; values: Array<number | null> }>;
  note: string | null;
}

export interface Finding {
  /** Stable for a client, period and entity: `${detector}:${entity.id}`. */
  id: string;
  detector: DetectorId;
  priority: InsightPriority;
  entity: InsightEntity;
  /** What happened, in one factual sentence. Never names a cause. */
  headline: string;
  /** Three or four metrics that prove the headline. */
  evidence: EvidenceItem[];
  /** Now / before / change rows relevant to the detector; may be empty. */
  comparison: ComparisonRow[];
  target: TargetRelation | null;
  chart: InsightChart | null;
  breakdown: InsightBreakdown | null;
  /** Advisory; never executed by the product. */
  action: string;
  /** Why this was flagged: the rule in plain language with the observed values. */
  reason: string;
  /** The one value a compact list leads with. */
  key: { value: number | null; format: ValueFormat; label: string };
  /** Ordering metadata: the current-period spend of the flagged entity. */
  spendInvolved: number;
}

/* ----------------------------------------------------------------------------
 * Facts: the source-agnostic input to the engine. Any data source (seed, CSV,
 * platform API) can produce these; the detectors never see a repository.
 * ------------------------------------------------------------------------- */

export interface EntityFacts {
  entity: InsightEntity;
  current: MetricSnapshot;
  previous: MetricSnapshot;
  /** Daily totals, previous and current periods, aligned by day index. */
  daily: { current: DailyPoint[]; previous: DailyPoint[] };
}

export interface CampaignFacts extends EntityFacts {
  status: EntityStatus;
  ads: EntityFacts[];
}

export interface CreativeFacts extends EntityFacts {
  creativeType: CreativeType;
  adCount: number;
  campaignCount: number;
}

export interface InsightContext {
  clientName: string;
  currency: CurrencyCode;
  vocabulary: ConversionVocabulary;
  /** Null when the client has no cost-per-conversion target. */
  targetCpa: number | null;
  /** Null when the client has no ROAS target. */
  targetRoas: number | null;
  tracksRevenue: boolean;
  /** Days in the selected period. */
  periodDays: number;
  /** The comparison baseline, e.g. "previous 7 days". */
  comparison: string;
}

export interface InsightFacts {
  context: InsightContext;
  account: EntityFacts;
  campaigns: CampaignFacts[];
  creatives: CreativeFacts[];
}
